name: Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          git clone https://github.com/Francesco149/oppai.git
          cd oppai/pyoppai
          python setup.py install
          cd ../..
      - name: Run tests with unittest
        run: python3 tests.py 
