name: Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        env:
          OSUAPIKEY: ${{ secrets.OSUAPIKEY }}
          OSUTOKEN: ${{ secrets.OSUTOKEN }}
        run: |
          echo "$OSUAPIKEY" > osuapikey
          python3 -m pip install aiohttp
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt -U
      - name: Run tests with unittest
        env:
          OSUAPIKEY: ${{ secrets.OSUAPIKEY }}
        run: |
          echo "$OSUAPIKEY" > osuapikey
          python3 tests.py 
